### ISSUE TITLE
Request Support for TDE 2.4

### ISSUE THREAD

**Issue by JustusPan** [thebitcave/ai-brain-extensions-for-topdown-engine#3]
Since TDE 2.4 have been released and there are some api broken changes, could you please help to update AI Brain Extensions to 2.4?

**Comment by marcosecchi** [comment]
Hello @JustusPan, thanks for reaching me out. Unfortunately at the moment I am involved in a fulltime projact and I have no spare time for updating this side project.
Probably I will get back to it but I don't have short term plans at the moment.
